/* eslint-disable */
export const userData = {
    id: 7725,
    nickname: "LMDx",
    is_subscribed_feed: false,
    is_subscribed_blog: false,
    subscribers: 0,
    followers: 0,
    nickname_migrate: false,
    first_name: "Nikita",
    last_name: "Kosarev",
    email: "nikita021103@mail.com",
    role: 1,
    social_id: "{\facebook\:\\,\google\:\\,\instagram\:\\}",
    avatar: 0,
    avatar_media: null,
    notification: 1,
    notif_msgs: 0,
    notif_comments: 0,
    notif_favevents: 0,
    notif_stories: 1,
    notif_follow: 1,
    notif_likes: 1,
    review_rate: null,
    created_at: "2023-03-14T15:17:22.000000Z",
    updated_at: "2023-03-14T15:17:22.000000Z",
    deleted_at: null,
    ur_fio: null,
    ur_name: null,
    ur_description: null,
    ur_ogrn: null,
    ur_inn: null,
    ur_kpp: null,
    ur_bik: null,
    ur_rekv: null,
    ur_address: null,
    ur_passport: null,
    ur_photo: null,
    phone: null,
    website: null,
    description: null,
    ur_legalname: null,
    ur_factaddress: null,
    ur_type: 7,
    lat: 0,
    long: 0,
    geo_added: null,
    full_name: "Kosarev Nikita",
    media: [],
    pets: [],
    reviews: [{
        id:1,
        avatar: null,
        name: "LMD",
        status: "Accept",
        application: 1245126,
        date: "декабрь 2021",
        raiting: 3,
        textReview: "Выражаю благодарность! Услуга оказан в срок и очень качественно. Рекомендую!"
    },{
        id:2,
        avatar: "https://reactnative.dev/img/tiny_logo.png",
        name: "LMD",
        status: "Accept",
        application: 1245126,
        date: "декабрь 2021",
        raiting: 4,
        textReview: "Выражаю благодарность! Услуга оказан в срок и очень качественно. Рекомендую!"
    },{
        id:3,
        avatar: "https://reactnative.dev/img/tiny_logo.png",
        name: "Nick",
        status: "Accept",
        application: 1245126,
        date: "декабрь 2021",
        raiting: 4,
        textReview: "Выражаю благодарность! Услуга оказан в срок и очень качественно. Рекомендую!"
    },{
        id:4,
        avatar: "https://reactnative.dev/img/tiny_logo.png",
        name: "Nikita",
        status: "Accept",
        application: 1245126,
        date: "декабрь 2021",
        raiting: 4,
        textReview: "Выражаю благодарность! Услуга оказан в срок и очень качественно. Рекомендую!"
    },{
        id:5,
        avatar: "https://reactnative.dev/img/tiny_logo.png",
        name: "Danil",
        status: "Accept",
        application: 1245126,
        date: "декабрь 2021",
        raiting: 4,
        textReview: "Выражаю благодарность! Услуга оказан в срок и очень качественно. Рекомендую!"
    },{
        id:6,
        avatar: "https://reactnative.dev/img/tiny_logo.png",
        name: "Stepan",
        status: "Accept",
        application: 1245126,
        date: "декабрь 2021",
        raiting: 4,
        textReview: "Выражаю благодарность! Услуга оказан в срок и очень качественно. Рекомендую!"
    },{
        id:7,
        avatar: "https://reactnative.dev/img/tiny_logo.png",
        name: "Oleg",
        status: "Accept",
        application: 1245126,
        date: "декабрь 2021",
        raiting: 4,
        textReview: "Выражаю благодарность! Услуга оказан в срок и очень качественно. Рекомендую!"
    },{
        id:8,
        avatar: "https://reactnative.dev/img/tiny_logo.png",
        name: "Victor",
        status: "Accept",
        application: 1245126,
        date: "декабрь 2021",
        raiting: 4,
        textReview: "Выражаю благодарность! Услуга оказан в срок и очень качественно. Рекомендую!"
    },{
        id:9,
        avatar: null,
        name: "Alex",
        status: "Accept",
        application: 1245126,
        date: "декабрь 2021",
        raiting: 4,
        textReview: "Выражаю благодарность! Услуга оказан в срок и очень качественно. Рекомендую!"
    },{
        id:10,
        avatar: "https://reactnative.dev/img/tiny_logo.png",
        name: "LMDX",
        status: "Accept",
        application: 1245126,
        date: "декабрь 2021",
        raiting: 4,
        textReview: "Выражаю благодарность! Услуга оказан в срок и очень качественно. Рекомендую!"
    }],
    events: [],
    event_comments: null,
    show_guides: 0
}